### ISSUE TITLE
Issues with Proxmox SSL

### ISSUE THREAD

**Issue by gsxdsm** [rgl/terraform-proxmox-talos#2]
I have trusted my proxmox self certs, but erroring out with: 

Error: error listing files from datastore local: received an HTTP 596 response - Reason: error:0A000086:SSL routines::certificate verify failed

Any tips?

**Comment by rgl** [comment]
not sure from where (e.g. what client) that error is coming from. this repository is ignoring the proxmox server certificate (e.g. it uses `export PROXMOX_VE_INSECURE='1'`, which should trigger the proxmox provider to set `insecure = true` as described at https://registry.terraform.io/providers/bpg/proxmox/latest/docs#example-usage).

but any certificate error is normally due to some problem configuring your client to trust whatever certification authority (CA) is used by your proxmox node certificate. you should also ensure that you are using a domain name (or IP address) that matches whatever is on the proxmox server certificate (i.e. in its Subject Alternative Name (SAN)). also note that, since the proxmox terraform provider is written in Go, you should read how to configure it tru environment variables as described at https://go.dev/src/crypto/x509/root_unix.go or tru files at https://go.dev/src/crypto/x509/root_linux.go and see whether that can help.
